### ISSUE TITLE
Generated typings file has bad import path and mixed slashes

### ISSUE THREAD

**Issue by nwinger** [EVRYAS/elementsui-react#42]
1. Run yarn
2. src/components/index.d.ts generates exports on the following format (Note `mentsui-react..` and mixed slashes)
`export { default as Spinner } from 'mentsui-react\src\components\Indicators/Spinner';`

As a result of this, the imports are working incorrectly when consumed in Elements.
`node_modules/elementsui-react/index.d.ts(1,35): error TS2307: Cannot find module 'mentsui-reactsrccomponentsInputs/Button'.`

**Comment by Kashkovsky** [comment]
slash-backslash issue in Win/Mac. Fixed
