### ISSUE TITLE
Button component is missing htmlId and onClick properties 

### ISSUE THREAD

**Issue by NeurotechDevelopment** [EVRYAS/elementsui-react#65]
Button component 
* missing htmlId property
* onClick handler is misspelled as onC**L**ick

Create typescript component and use Button example code:

```
import * as React from 'react'
import Button from 'elementsui-react/Inputs/Button'

export class ButtonTest extends React.Component {
	constructor(props: any) {
		super(props)		
	}

	render() {		
		return <Button
		htmlId="primaryClickBtn"
		label="Click me"
		isPrimary={true}
		onClick={() => alert('Clicked')}
		className="button-click"
	/>
	}
}

export default ButtonTest
```
Expected
Mentioned properties are defined

Actual
no htmlId
![button_htmlid](https://user-images.githubusercontent.com/24508103/41031282-f1cb1fec-6988-11e8-9ac0-14772d6910de.png)

misspelled onClick
![button_onclick](https://user-images.githubusercontent.com/24508103/41031381-297691f6-6989-11e8-8976-1f3641c0cdf8.png)

**Comment by Kashkovsky** [comment]
Fixed in elementsui-react@0.1.31
